# specific branch build with batching
trigger:
  batch: true
  branches:
    include:
    - main

webhooks HTTP/HTTPS
- push 
- post 
- get 
resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ACR'
        repository: 'practice12'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
